### ISSUE TITLE
Incompatible with RM 2019.2 EAP

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#40]
JB is at it again. Just installed the latest `2019.2 EAP` and railways doesn't work anymore.

<img width="421" alt="Screen Shot 2019-06-03 at 9 40 30 AM" src="https://user-images.githubusercontent.com/1774502/58806359-fff7a180-85e3-11e9-931f-4c37bec86ee0.png">

```
RubyMine 2019.2 EAP
Build #RM-192.4205.37, built on May 23, 2019
Runtime version: 11.0.3+12-b248.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13
```

**Comment by davidteren** [comment]
Any news on this?

**Comment by basgren** [comment]
Hi guys.
This is not JB to blame, this is just selected policy of plugin updates. To make sure the plugin doesn't break new versions of IDE, I just restrict plugin compatibility to the most recent version (like "compatible with 2019.1 only"). While this approach works good for frequently updated plugins, in my case it's a bit time consuming - I have to rebuild the plugin with updated restrictions and without any significant changes each time new IDE version is out. So I decided to switch back to the old approach, when only lower compatible IDE version is set (like "compatible with 2019.1 and above"). So since now plugin will cause problems only when there are indeed some significant API changes in new IDE. I think that would be not so often and that's why we have EAPs for - to test everything works fine before stable release)))

In the meantime I've built new version of Railways plugin (0.8.15), feel free to check it. Please let me know it everything works fine.

Regards.

**Comment by thestelz** [comment]
@basgren I have been using this all week and haven't had any issues. Thanks for getting this out! I really enjoy using this plugin. Saves me a lot of time
