### ISSUE TITLE
Failed to load routes in Rails 6.1

### ISSUE THREAD

**Issue by eclectic-coding** [basgren/railways#48]
Title says it all.
After a little research, it seems, `rake routes` is not available in Rails 6.1 as a task, by default. However, `rails routes` works fine. 

You might consider a fix. Would hate to see this plugin unusable, I depend on it so much.

**Comment by dkimot** [comment]
The problem is https://github.com/basgren/railways/blob/master/src/net/bitpot/railways/utils/RailwaysUtils.java#L84.

I'm not a java dev and loading the project in idea produces a bunch of errors. Apparently `org.jetbrains.plugins.ruby.gem` and `org.jetbrains.plugins.ruby.ruby` packages don't exist in the sdk setup I'm using. I have no idea why, I've never done Java. They could be deprecated libraries or it could be a PEBKAC issue. 🤷

**Comment by falegk** [comment]
The `rake routes` task has removed from RoR 6.1 
https://edgeguides.rubyonrails.org/6_1_release_notes.html#railties-removals

A temporary solution, not so beautiful but it works until this plugin to be updated for the 6.1 rails version.

create lib/tasks/routes.rake

```
desc "Just implements the rake routes task..."
task :routes => :environment do
  puts `rails routes`
end
```

**Comment by eclectic-coding** [comment]
@falegk this option does work, but as you said is "not so beautiful." This option would require me to add a new rake task on every project I create, not ideal but a work around. 

Thanks for the temporary solution.

**Comment by entretechno-nic** [comment]
I've submitted a PR for this based on @dkimot's suggestion.

**Comment by basgren** [comment]
Gentlemen, I apologize for the delay. I've applied and tested the fix and will release new release soon. Thank you for your help!
